//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriThucOnline_TTN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAUSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAUSACH()
        {
            this.CT_HOADON = new HashSet<CT_HOADON>();
        }
    
        public int Masach { get; set; }
        public string Tensach { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<int> MaTL { get; set; }
        public Nullable<int> MaTG { get; set; }
        public Nullable<int> Namxuatban { get; set; }
        public Nullable<double> Price { get; set; }
        public string PicBook { get; set; }
        public Nullable<int> Sotrang { get; set; }
        public string Bocucsach { get; set; }
        public string Trichdan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
        public virtual NXB NXB { get; set; }
    }
}
